Port Unanswered Frequently Asked Questions From Old Docs
near/docs pull request #1091
Opened 2022-06-21 15:27 UTC by idea404

This PR adds a FAQ section in `develop` that answers questions unanswered by the text currently in `newdocs`

2022-06-22 09:59 UTC, gagdiez commented
I would rather add each question in the section it would belong (i.e. anatomy, environment, storage) than in a separated FAQ, since in that way we make then simpler to find. Otherwise, people doesn't know if they should go to the page related to the problem, or to search in the FAQ.

2022-06-23 11:48 UTC, idea404 commented
> I would rather add each question in the section it would belong (i.e. anatomy, environment, storage) than in a separated FAQ, since in that way we make then simpler to find. Otherwise, people doesn't know if they should go to the page related to the problem, or to search in the FAQ.

Have removed FAQ-dedicated page and moved questions to relevant areas @gagdiez

2022-06-24 09:23 UTC, gagdiez requested changes

2022-06-24 09:23 UTC, gagdiez commented on docs/2.develop/contracts/anatomy.md
> +storage.get("my-var", "hello, default")!; // notice the ! at the end
this is more pertinent to the storage section

2022-06-24 09:23 UTC, gagdiez commented on docs/2.develop/deploy.md
> +<blockquote class="lesson">
We should transform this into a sub-section talking about what happens when you deploy a contract into an account that already has a contract.

2022-06-24 09:23 UTC, gagdiez commented on docs/3.tools/welcome.md
> +## What's the timeline/plan for supporting general widely used programming languages so devs can just code in whatever they're comfortable working with?
This can go into develop/whatiscontract ,  there is a section about programming languages.

2022-06-24 09:23 UTC, gagdiez commented on docs/2.develop/contracts/anatomy.md
> +## Building Smart Contracts on an Apple M1 Machine (arm64) {#building-smart-contracts-on-apple-m1-arm64}
this is more pertinent for the deploy section

2022-06-27 08:28 UTC, idea404 commented
@gagdiez, what do you think?

2022-06-29 13:04 UTC, merged