NFT Series 9th Installement
near/docs pull request #1138
Opened 2022-08-20 14:33 UTC by BenKurrek

Go Team

2022-08-22 20:57 UTC, bucanero commented on docs/3.tutorials/nfts/8-marketplace.md
> +You should now have a solid understanding of NFTs and marketplaces on NEAR. Feel free to branch off and expand on these contracts to create whatever cool applications you'd like. In the next tutorial
```suggestion
You should now have a solid understanding of NFTs and marketplaces on NEAR. Feel free to branch off and expand on these contracts to create whatever cool applications you'd like. In the [next tutorial](9-series.md), you'll learn how to take the existing NFT contract and optimize it to allow for:
```

2022-08-22 20:58 UTC, bucanero commented on docs/3.tutorials/nfts/9-series.md
> +In this tutorial, you'll learn how to take the existing NFT contract you've been working with and modify it to meet some of the most common needs I've seen in the ecosystem. This includes:
```suggestion
In this tutorial, you'll learn how to take the existing NFT contract you've been working with and modify it to meet some of the most common needs in the ecosystem. This includes:
```

2022-08-22 21:00 UTC, bucanero commented on docs/3.tutorials/nfts/9-series.md
> +One of the biggest problems with the current NFT repo is repeated data. Currently, if you mint NFTs, you'll need to store the metadata in the contract every single time. While this is fine for NFTs t
```suggestion
One of the biggest problems with the current NFT repository is repeated data. Currently, if you mint NFTs, you'll need to store the metadata in the contract every single time. While this is fine for NFTs with drastically different metadata, having repeated similar data is screaming for optimization. In addition, one of the most common use cases for NFTs currently is *collections*.
```

2022-08-22 21:01 UTC, bucanero commented on docs/3.tutorials/nfts/9-series.md
> +A collection is a set of NFTs that are related to each other in some way. More often that not, this means they share the same media, title, description, number of copies etc. If you wanted to make a
```suggestion
A collection is a set of NFTs that are related to each other in some way. More often than not, this means they share the same media, title, description, number of copies, etc. If you wanted to make a collection of 1000 NFTs with the current contract, you'd need to store this duplicate information 1000 times when the only thing changing between the NFTs in the collection is the token ID. We can fix this by introducing the idea of a series. 
```

2022-08-22 21:05 UTC, bucanero commented on docs/3.tutorials/nfts/9-series.md
> +Benji has created an amazing digital painting of the famous Go Team gif. He wants to sell 1000 copies of it for 1 $NEAR each. Using the traditional approach, he would have to mint each copy individua
```suggestion
Benji has created an amazing digital painting of the famous Go Team gif. He wants to sell 1000 copies of it for 1 $NEAR each. Using the traditional approach, he would have to mint each copy individually and pay for the storage himself. He would then need to pay for the storage to put 1000 copies up for sale on a marketplace contract, and he would need to put each up for sale **individually** which would cost a lot in Gas. After that, people would purchase the NFTs, and there would be no guarantee that all or even any would be sold. There's a real possibility that nobody buys a single piece of his artwork, and Benji spent all that time and effort and money on nothing. 😢  
```

2022-08-22 21:17 UTC, bucanero commented on docs/3.tutorials/nfts/9-series.md
> +Thank you so much for going through this journey with us! I wish you all the best and am eager to see what sorts of neat and unique use-cases you can come up with. If you have any questions, feel fre
```suggestion
Thank you so much for going through this journey with us! I wish you all the best and am eager to see what sorts of neat and unique use-cases you can come up with. If you have any questions, feel free to ask on our Discord or any other social media channels we have.
```

2022-08-22 21:17 UTC, bucanero approved these changes

2022-08-24 01:44 UTC, thisisjoshford requested changes
WIP: Left a few suggestions and comments and stopped at line 175. 

Will continue later :)

2022-08-24 01:44 UTC, thisisjoshford commented on docs/3.tutorials/nfts/9-series.md
> +Most of the information is the same, although we've added 2 new lookup sets and we've changed the `token_metadata_by_id` to be `series_by_id`.
```suggestion
As you can see, we've replaced `token_metadata_by_id` with `series_by_id` and added two lookup sets:
```

2022-08-24 01:44 UTC, thisisjoshford commented on docs/3.tutorials/nfts/9-series.md
> +- **series_by_id**: Map a series ID (u64) to its Series object.
```suggestion
- **series_by_id**: Map a series ID (u64) to its Series object.

- **approved_minters**: Keeps track of accounts that can call the `nft_mint` function.
- **approved_creators**: Keeps track of accounts that can create new series.
```

2022-08-24 01:44 UTC, thisisjoshford commented on docs/3.tutorials/nfts/9-series.md
> +- The price.
I would add links to these for further explanation / reminders

2022-08-24 01:44 UTC, thisisjoshford commented on docs/3.tutorials/nfts/9-series.md
> +If a price is specified, there will be no restriction on who can mint tokens in the series. In addition, if the `copies` field is specified in the metadata, **only** that number of NFTs can be minted
I would add a "Heads Up" `:::caution` flag here

2022-08-24 01:44 UTC, thisisjoshford commented on docs/3.tutorials/nfts/9-series.md
> +Moving on to a new file that has been introduced, you'll notice that there's no longer the `mint.rs` file and it's been replaced by a newer `series.rs` file. This is responsible for everything relate
```suggestion
`series.rs` is a new file that replaces the old `mint.rs` logic. This is responsible for everything related to creating a series as well as minting NFTs using the `create_series` method.
```

2022-08-24 01:44 UTC, thisisjoshford commented on docs/3.tutorials/nfts/9-series.md
> +The function takes in a series ID in the form of a `u64`, the metadata, royalties, and the price for tokens in the series. It will then create the `Series` object and insert it into the contract's `s
I would link `u64`, `Series` object, and `series_by_id` struct so people can have easy ways to learn more about something they don't yet understand. 

As much as we want users to follow a narrative that we create.... that can often not be the case as people skip to a section they want to learn about or (more likely a case) that people land on a section from a search.

2022-08-24 01:44 UTC, thisisjoshford commented on docs/3.tutorials/nfts/9-series.md
> +
```suggestion
Next, we'll look at the minting function. 

In the basic version of the NFT smart contract there are several required parameters:
- Token ID
- Metadata
- Receiver ID
- Perpetual Royalties 

With the new contract, we've reduced this to two arguments:
- The series ID
- The receiver ID.

```

2022-08-24 01:44 UTC, thisisjoshford commented on docs/3.tutorials/nfts/9-series.md
> +Notice how the token ID isn't required? This is because the token ID is automatically generated when minting. The ID is stored on the contract as `${series_id}:${token_id}` where the token ID is a no
Could add a `:::tip` banner for this section or `:::info`

2022-08-24 01:44 UTC, thisisjoshford commented on docs/3.tutorials/nfts/9-series.md
> +The mint function will charge users for storage and if the series has a price, it will ensure that users attach enough $NEAR to cover the price **and** storage. At the end, it will then send all the
This section is a little confusing. Let's take a stab at re-wording this to be a little more clear.

2022-08-24 01:44 UTC, thisisjoshford commented on docs/3.tutorials/nfts/9-series.md
> +Now that we've introduced the idea of series, more view functions have been added to support the potentially complex use cases that arise with this contract. With these functions, a new `JsonSeries`
```suggestion
Now that you are using a `Series` structure for your NFT contract, retrieving on-chain data from these contracts will require you to create new `view` methods. 

Here we will use a new struct (`JsonSeries`) that will store the metadata for each series.
```

2022-08-24 01:44 UTC, thisisjoshford commented on docs/3.tutorials/nfts/9-series.md
> +Now that we've introduced the idea of series, more view functions have been added to support the potentially complex use cases that arise with this contract. With these functions, a new `JsonSeries`
Lmk if line 165 is accurate. Explaining the serialization of an unordered set might be unnecessary here and more appropriate in the area where we outline the `JsonSeries` struct.

2022-09-08 11:44 UTC, merged