Update node providers
near/docs pull request #1313
Opened 2022-12-05 16:31 UTC by AnnaNodes

Hello,

We are a Near node provider NOWNodes.
May you update the node providers list?

2022-12-07 15:03 UTC, bucanero commented
Sorry, but the `http://bit.do/nownodes-near/` URL brings a 404 page.

2022-12-07 15:03 UTC, bucanero requested changes
404 URL

2022-12-13 17:41 UTC, bucanero commented on docs/5.api/rpc/providers.md
> +| `http://bit.do/freeapikey-near` | NOWNodes |    http://bit.do/freeapikey-near     |
```suggestion
| `http://bit.do/freeapikey-near` | NOWNodes |    https://nownodes.io/     |
```

2022-12-13 17:41 UTC, bucanero approved these changes

2022-12-13 17:41 UTC, merged

2023-05-26 14:44 UTC, AnnaNodes commented
Hello Damián, 

You were helping me with the NEAR indexer on LinkedIn.

Could you please change the NOWNodes link to https://nownodes.io/nodes?

Thank you!
Anna

2023-05-26 17:13 UTC, bucanero commented
> Hello Damián, 
> 
> 
> 
> You were helping me with the NEAR indexer on LinkedIn.
> 
> 
> 
> Could you please change the NOWNodes link to https://nownodes.io/nodes?
> 
> 
> 
> Thank you!
> 
> Anna 

I'm currently OOO but if it's urgent, feel free to open a PR with the new URL and we'll merge it