Update "Building Smart Contracts" Quickstart to use near-cli-rs
near/docs pull request #1638
Opened 2023-12-29 23:49 UTC by elliotBraem

Now uses near-cli-rs (https://github.com/near/near-cli-rs/issues/235)

2024-01-01 20:57 UTC, dbejarano820 approved these changes

2024-01-02 09:55 UTC, gagdiez requested changes
Hi Elliot, thanks for the contribution!. It would be better to provide both experiences, for which we can use tabs.

2024-01-16 16:31 UTC, gagdiez commented on docs/2.develop/contracts/quickstart.md
> +> near contract call-function as-read-only as-read-only <created-account> get_greeting
```suggestion
> near contract call-function as-read-only <created-account> get_greeting
```

2024-01-17 14:30 UTC, bucanero approved these changes

2024-01-17 14:56 UTC, merged