update link for examples
near/docs pull request #1700
Opened 2024-02-01 01:23 UTC by matiasbenary

2024-02-01 10:17 UTC, gagdiez requested changes
most of the links should be "context aware", for example:
- if we talk about the JS contract, then we need to point to the contract
- if we talk about the frontend, then we need to point to the frontend

2024-02-01 14:29 UTC, matiasbenary commented on docs/3.tutorials/crosswords/02-beginner/05-logging-in.md
> +If I log into the [Guest Book example site](https://github.com/near-examples/guest-book-examples), I create a unique key just for that dApp, adding it to my account. When I'm done I can remove the ke
```suggestion
If I log into the [Guest Book example site](https://github.com/near-examples/guest-book-examples/tree/main/frontend), I create a unique key just for that dApp, adding it to my account. When I'm done I can remove the key myself. If I suspect someone has control of my key (if a laptop is stolen, for example) I can remove the key as long as I have a full-access key in my control.
```

2024-02-01 14:33 UTC, matiasbenary commented on docs/sdk/js/intro.md
> +If you only wish to develop and deploy a JS contract, the [`hello-near-js`](https://github.com/near-examples/hello-near-examples) repository is great to use as a template or one of the [examples in t
```suggestion
If you only wish to develop and deploy a JS contract, the [`hello-near-ts`](https://github.com/near-examples/hello-near-examples/tree/main/contract-ts) repository is great to use as a template or one of the [examples in the SDK repository](https://github.com/near/near-sdk-js/tree/develop/examples/src).
```

2024-02-08 15:11 UTC, gagdiez commented on docs/3.tutorials/examples/donation.md
> +1. The smart contract, available in two flavours: rust and javascript
```suggestion
1. The smart contract, available in two flavors: rust and javascript
```

2024-02-08 15:34 UTC, gagdiez approved these changes

2024-02-08 15:34 UTC, merged