Improved relayer learn and build pages
near/docs pull request #1820
Opened 2024-03-16 17:22 UTC by SurgeCode

2024-03-18 12:14 UTC, bucanero commented on docs/1.concepts/abstraction/relayers.md
> +Relayers are a natural consequence of [NEP-366: Meta Transactions](https://github.com/near/NEPs/blob/master/neps/nep-0366.md), a special type of transaction which can be best understood as an intent.
```suggestion
Relayers are a natural consequence of [Meta Transactions](meta-tx.md) ([NEP-366](https://github.com/near/NEPs/blob/master/neps/nep-0366.md)), a special type of transaction that can be best understood as an intent.
```

2024-03-18 12:17 UTC, bucanero commented on docs/2.develop/relayers/welcome.md
> +If you're already aquainted with the technology you can fast track to a [working open source example](https://github.com/SurgeCode/near-relay-example)
```suggestion
If you're already acquainted with the technology, you can fast track to a [working open source example](https://github.com/SurgeCode/near-relay-example) 
```

2024-03-19 10:55 UTC, bucanero commented on docs/2.develop/relayers/welcome.md
> +If you're already acquainted with the technology, you can fast track to a [working open source example](https://github.com/SurgeCode/near-relay-example)
```suggestion
:::tip

If you're already acquainted with the technology, you can fast track to a [working open source example](https://github.com/SurgeCode/near-relay-example) 

:::
```

2024-03-19 17:12 UTC, bucanero requested changes
hello @SurgeCode , thanks for the PR.

It seems that some images that you are linking are missing:

```
/docs/assets/welcome-pages/relayer-overview.png
/docs/assets/welcome-pages/relayer-overview-technical.png
```

can you add the missing files, or remove the references? thanks!

2024-03-25 15:25 UTC, SurgeCode commented
> hello @SurgeCode , thanks for the PR.
> 
> It seems that some images that you are linking are missing:
> 
> ```
> /docs/assets/welcome-pages/relayer-overview.png
> /docs/assets/welcome-pages/relayer-overview-technical.png
> ```
> 
> can you add the missing files, or remove the references? thanks!

Thanks for the heads up, added them

2024-03-25 15:33 UTC, bucanero approved these changes

2024-03-25 15:37 UTC, merged