Add 'Run a Relayer' article
near/docs pull request #1897
Opened 2024-04-10 20:50 UTC by bucanero

2024-04-11 13:12 UTC, gagdiez commented
what would be the main difference with the current relayer docs? Maybe we could just add the pagoda's relayer as an example of a relayer, or maybe examples on how to use it as an endpoint

2024-04-11 17:10 UTC, ravigautham commented
@bucanero I think I agree with @gagdiez's comment above. Instead of this being a separate article, we should add this as a rust implementation of a relayer server on the original article. Maybe this article can somehow be integrated into the already existing "Building a Relayer" article? Or maybe we can rename that to be "Meta Transaction Relayers" to keep it more general? 

But other than that I think the content of the article is clear and solid.

2024-04-11 17:22 UTC, anthony-near requested changes
@bucanero everything looks good except for the omission of `/sign_meta_tx_*` endpoints and the creation of the account keys json file, which should have brackets around the json `[ ... ]`. That was my fault for not updating the readme with the appropriate instructions. README updates here: https://github.com/near/pagoda-relayer-rs/pull/89/files

2024-04-11 17:23 UTC, anthony-near commented on docs/2.build/1.chain-abstraction/multichain-gas-relayer/run-relayer.md
> +   {"account_id":"example.testnet","public_key":"ed25519:98GtfFzez3opomVpwa7i4m3nptHtc7Ha514XHMWszLtQ","private_key":"ed25519:YWuyKVQHE3rJQYRC3pRGV56o1qEtA1PnMYPDEtroc5kX4A4mWrJwF7XkzGe7JWNMABbtY4XFD
add `[ ... ]` https://github.com/near/pagoda-relayer-rs/pull/89/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R102

2024-04-11 21:19 UTC, bucanero commented on docs/2.build/1.chain-abstraction/multichain-gas-relayer/run-relayer.md
> +   {"account_id":"example.testnet","public_key":"ed25519:98GtfFzez3opomVpwa7i4m3nptHtc7Ha514XHMWszLtQ","private_key":"ed25519:YWuyKVQHE3rJQYRC3pRGV56o1qEtA1PnMYPDEtroc5kX4A4mWrJwF7XkzGe7JWNMABbtY4XFD
fixed

2024-04-11 21:20 UTC, bucanero commented on docs/2.build/1.chain-abstraction/multichain-gas-relayer/run-relayer.md
> +1. Cover the gas costs of end users while allowing them to maintain custody of their funds and approve transactions (`/relay`, `/send_meta_tx`, `/send_meta_tx_async`, `/send_meta_tx_nopoll`)
fixed

2024-04-11 21:20 UTC, anthony-near approved these changes

2024-04-12 16:31 UTC, ravigautham approved these changes
Looks great!

2024-04-12 20:45 UTC, merged