Edit protocol basics to improve readability
near/docs pull request #1942
Opened 2024-04-29 22:49 UTC by s-n-park

Edited wording a bit to try and improve readability

Flesch-Kincaid Score previous: 35.39
After re-work: 50.2

2024-04-30 11:02 UTC, gagdiez requested changes

2024-04-30 11:02 UTC, gagdiez commented on docs/1.concepts/basics/protocol.md
> +4. Earn 30% of gas fees
```suggestion
4. Earn from your contract's gas fees
```

2024-04-30 11:02 UTC, gagdiez commented on docs/1.concepts/basics/protocol.md
> +4. Earn 30% of gas fees
I see our original version is a bit misleading

2024-05-01 22:12 UTC, s-n-park commented on docs/1.concepts/basics/protocol.md
> +1. [**Named accounts**](../protocol/account-model.md) let you use easy names like `alice.near`.
I revised to:
> [**Named accounts**](../protocol/account-model.md) let you use easily remember and share names like `alice.near` for your blockchain addresses.

But lmk if you think the original is still clearer happy to change it back:
> Accounts are easy to remember and share thanks to built-in [**Named accounts**](../protocol/account-model.md) (as `alice.near`)

2024-05-02 14:07 UTC, gagdiez commented on docs/1.concepts/basics/protocol.md
> +1. [**Named accounts**](../protocol/account-model.md) let you use easily remember and share names like `alice.near` for your blockchain addresses.
```suggestion
1. Use [**named accounts**](../protocol/account-model.md) like `alice.near`
```

2024-05-02 14:07 UTC, gagdiez approved these changes

2024-05-02 14:07 UTC, merged