Add UI frontend article
near/docs pull request #2059
Opened 2024-06-15 00:02 UTC by bucanero

2024-06-17 15:39 UTC, calebjacob approved these changes

2024-06-18 18:17 UTC, mpeterdev requested changes
please hold on merge, I am going to suggest some additions/modifications

2024-06-18 22:17 UTC, bucanero commented on docs/2.build/3.near-components/what-is.md
> +See [here](/build/web3-apps/frontend#bos-socialvm) for more info
```suggestion
See [here](/build/web3-apps/frontend#bos-socialvm) for more information.
```

2024-06-18 22:17 UTC, bucanero commented on docs/2.build/3.near-components/environment.md
> +See [here](/build/web3-apps/frontend#bos-socialvm) for more info
```suggestion
See [here](/build/web3-apps/frontend#bos-socialvm) for more information.
```

2024-06-18 22:17 UTC, bucanero commented on docs/2.build/3.near-components/bos-gateway.md
> +See [here](/build/web3-apps/frontend#bos-socialvm) for more info
```suggestion
See [here](/build/web3-apps/frontend#bos-socialvm) for more information.
```

2024-06-18 22:17 UTC, bucanero commented on docs/2.build/3.near-components/anatomy/web-methods.md
> +See [here](/build/web3-apps/frontend#bos-socialvm) for more info
```suggestion
See [here](/build/web3-apps/frontend#bos-socialvm) for more information.
```

2024-06-18 22:17 UTC, bucanero commented on docs/2.build/3.near-components/anatomy/state.md
> +See [here](/build/web3-apps/frontend#bos-socialvm) for more info
```suggestion
See [here](/build/web3-apps/frontend#bos-socialvm) for more information.
```

2024-06-18 22:17 UTC, bucanero commented on docs/2.build/3.near-components/anatomy/social.md
> +See [here](/build/web3-apps/frontend#bos-socialvm) for more info
```suggestion
See [here](/build/web3-apps/frontend#bos-socialvm) for more information.
```

2024-06-18 22:17 UTC, bucanero commented on docs/2.build/3.near-components/anatomy/notifications.md
> +See [here](/build/web3-apps/frontend#bos-socialvm) for more info
```suggestion
See [here](/build/web3-apps/frontend#bos-socialvm) for more information.
```

2024-06-18 22:18 UTC, bucanero commented on docs/2.build/3.near-components/anatomy/near.md
> +See [here](/build/web3-apps/frontend#bos-socialvm) for more info
```suggestion
See [here](/build/web3-apps/frontend#bos-socialvm) for more information.
```

2024-06-18 22:18 UTC, bucanero commented on docs/2.build/3.near-components/anatomy/builtin-components.md
> +See [here](/build/web3-apps/frontend#bos-socialvm) for more info
```suggestion
See [here](/build/web3-apps/frontend#bos-socialvm) for more information.
```

2024-06-18 22:18 UTC, bucanero commented on docs/2.build/3.near-components/anatomy/bos-components.md
> +See [here](/build/web3-apps/frontend#bos-socialvm) for more info
```suggestion
See [here](/build/web3-apps/frontend#bos-socialvm) for more information.
```

2024-06-18 22:21 UTC, bucanero commented on docs/2.build/3.near-components/anatomy/bos-components.md
> +See [here](/build/web3-apps/frontend#bos-socialvm) for more information.
```suggestion
See the [Web3 frontends](/build/web3-apps/frontend#bos-socialvm) section for more information.
```

2024-06-18 22:21 UTC, bucanero commented on docs/2.build/3.near-components/anatomy/builtin-components.md
> +See [here](/build/web3-apps/frontend#bos-socialvm) for more information.
```suggestion
See the [Web3 frontends](/build/web3-apps/frontend#bos-socialvm) section for more information.
```

2024-06-18 22:22 UTC, bucanero commented on docs/2.build/3.near-components/anatomy/near.md
> +See [here](/build/web3-apps/frontend#bos-socialvm) for more information.
```suggestion
See the [Web3 frontends](/build/web3-apps/frontend#bos-socialvm) section for more information.
```

2024-06-18 22:22 UTC, bucanero commented on docs/2.build/3.near-components/anatomy/notifications.md
> +See [here](/build/web3-apps/frontend#bos-socialvm) for more information.
```suggestion
See the [Web3 frontends](/build/web3-apps/frontend#bos-socialvm) section for more information.
```

2024-06-18 22:22 UTC, bucanero commented on docs/2.build/3.near-components/anatomy/social.md
> +See [here](/build/web3-apps/frontend#bos-socialvm) for more information.
```suggestion
See the [Web3 frontends](/build/web3-apps/frontend#bos-socialvm) section for more information.
```

2024-06-18 22:22 UTC, bucanero commented on docs/2.build/3.near-components/anatomy/state.md
> +See [here](/build/web3-apps/frontend#bos-socialvm) for more information.
```suggestion
See the [Web3 frontends](/build/web3-apps/frontend#bos-socialvm) section for more information.
```

2024-06-18 22:23 UTC, bucanero commented on docs/2.build/3.near-components/anatomy/web-methods.md
> +See [here](/build/web3-apps/frontend#bos-socialvm) for more information.
```suggestion
See the [Web3 frontends](/build/web3-apps/frontend#bos-socialvm) section for more information.
```

2024-06-18 22:23 UTC, bucanero commented on docs/2.build/3.near-components/bos-gateway.md
> +See [here](/build/web3-apps/frontend#bos-socialvm) for more information.
```suggestion
See the [Web3 frontends](/build/web3-apps/frontend#bos-socialvm) section for more information.
```

2024-06-18 22:23 UTC, bucanero commented on docs/2.build/3.near-components/environment.md
> +See [here](/build/web3-apps/frontend#bos-socialvm) for more information.
```suggestion
See the [Web3 frontends](/build/web3-apps/frontend#bos-socialvm) section for more information.
```

2024-06-18 22:23 UTC, bucanero commented on docs/2.build/3.near-components/what-is.md
> +See [here](/build/web3-apps/frontend#bos-socialvm) for more information.
```suggestion
See the [Web3 frontends](/build/web3-apps/frontend#bos-socialvm) section for more information.
```

2024-06-18 22:26 UTC, bucanero commented
Hi @mpeterdev 👋 I've merged your changes and adjusted some minor details.

Let me know if you have more suggestions 🙏 thank you!

2024-06-20 15:01 UTC, mpeterdev approved these changes

2024-06-20 15:46 UTC, merged