(indexer) Add tools/near-indexer-framework document with almost everything about the NEAR Indexer Framework
near/docs pull request #711
Opened 2021-05-24 15:38 UTC by khorolets

* Move `tools/near-indexer.md` to `tutorials/near-indexer.md`
* Add `tools/near-indexer-framework.md` describing NEAR Indexer Framework
* Update `sidebar.json` a little bit to include those pages
* Add some crosslinks
* Replace the link to NEAR Indexer Framework in `concepts/indexer.md` to point to new document instead of github
 
Basically, we had this entire doc divided into pieces in different places. So @frol and I decided to combine and put in in the docs, so we can refer to it from `README`s

2021-05-24 15:42 UTC, khorolets commented
@thisisjoshford I suggest not to merge it until @frol approves :)

2021-05-24 17:07 UTC, frol approved these changes
We should add a redirect for the moved page

2021-05-24 17:07 UTC, frol commented on docs/tools/near-indexer-framework.md
> +As you see NEAR Indexer Framework is a tool, it's not an indexer itself. It is used to create you own indexer. You can find some tutorials about it in the docs:
```suggestion
As you see NEAR Indexer Framework is a tool, it's not an indexer itself. It is used to create your own indexer. You can find some tutorials about it in the docs:
```

2021-05-24 17:17 UTC, khorolets commented
> We should add a redirect for the moved page
@thisisjoshford I'd appreciate your help with this.

2021-05-25 08:46 UTC, frol approved these changes

2021-06-01 21:13 UTC, thisisjoshford commented
> > We should add a redirect for the moved page
> 
> @thisisjoshford I'd appreciate your help with this.

absolutely can help redirect this once its merged @khorolets .

2021-06-01 21:14 UTC, thisisjoshford requested changes
Looks like CI is failing due to broken links... Can you fix them before merging this @khorolets ?

2021-06-02 05:55 UTC, khorolets commented
@thisisjoshford I have tried, but there are no `docs/evm/*` and I've failed to fix that :)

2021-06-09 03:25 UTC, thisisjoshford approved these changes
Seems that there was still a merge conflict with `sidebars.json`. I resolved the conflict and pushed changes @khorolets . You're good to merge when ready.

2021-06-09 09:05 UTC, khorolets commented
> absolutely can help redirect this once its merged @khorolets .

I'm merging it, thanks!

2021-06-09 09:06 UTC, merged