Add possible errors info to JSON RPC methods
near/docs pull request #811
Opened 2021-08-16 10:17 UTC by khorolets

Introduce as much as possible information about possible errors for each JSON RPC method we have. Yet there is a lot of copy-paste data I believe it's one of the most readable ways to show errors.

This PR needs some attention to the language because it's me, you know.

**NB** this PR is based on #801 I am marking this as a draft until that one is merged.

2021-08-16 14:44 UTC, bucanero commented
Hi @khorolets,
#801 has been merged, so you should be unblocked now 👍

2021-08-16 15:26 UTC, khorolets commented
> Hi @khorolets,
> #801 has been merged, so you should be unblocked now 👍

Thanks for the heads up! I've resolved conflicts and marked PR as ready for review!

2021-08-18 17:59 UTC, frol requested changes
> The requested block can't be found in a database

I suggest considering the following: "The requested block has not been produced yet or it has been garbage-collected (cleaned up to save space on the RPC node)"

> If the block had been produced more than 5 epochs ago, try to send your request to an archival node

Let's add a reference on "archival node" to this section: https://docs.near.org/docs/develop/node/intro/types-of-node#archival-node (please, extend the section with URLs to mainnet and testnet archival nodes)

> The requested `account_id` has not been found while viewing

Maybe extend it with: "The requested `account_id` has not been found while viewing since the account has not been created or has been already deleted"

(apply the same about public keys and maybe some other places)

> Request a different block

"Specify a different block or retry if you request the latest state"

> The requested `contract_code` has not been found while viewing

"The account does not have any contract deployed on it"

There are no sane solutions to this one, I believe. Maybe suggest using a different account or deploying a contract to the queried account, but that is a bit of a stretch.

`NO_CONTRACT_CODE` should not happen on View contract state.

Please, double-check if `REQUEST_ROUTED` can actually happen on `broadcast_tx_commit`.

> Note that this does not mean transaction execution is failed not it means everything is fine.

"Note this does not mean the transaction execution failed nor it means everything is fine."

There is a typo in `error.cause.info.transactioc_hash`

`UNKNOWN_TRANSACTION` and `UNKNOWN_RECEIPT`:

> The requested transaction does not exist

"The requested transaction is not available on the node since it might have not been recorded on the chain yet or has been garbage-collected"

Solutions:
* Try again later
* If the transaction had been submitted more than 5 epochs ago, try to send your request to an archival node
* Check the transaction hash

2021-08-19 10:38 UTC, frol approved these changes
I found a few minor bugs. Once those are resolved, I believe we are good to go and address the rest of the minor issues (if any) in separate PRs.

2021-08-19 10:38 UTC, frol commented on docs/api/rpc/transactions.md
> +      <td rowspan="3">HANDLER_ERROR</td>
```suggestion
      <td rowspan="2">HANDLER_ERROR</td>
```

![image](https://user-images.githubusercontent.com/304265/130052415-70042ad5-74a5-4e97-a347-eddeb4bd6158.png)

2021-08-19 10:38 UTC, frol commented on docs/api/rpc/transactions.md
> +Here is the exhaustive list of the error variants that can be returned by `chunk` method:
```suggestion
Here is the exhaustive list of the error variants that can be returned by `broadcast_tx_commit` method:
```

2021-08-19 10:38 UTC, frol commented on docs/api/rpc/transactions.md
> +Here is the exhaustive list of the error variants that can be returned by `chunk` method:
```suggestion
Here is the exhaustive list of the error variants that can be returned by `broadcast_tx_async` method:
```

Please, check the rest.

2021-08-19 20:36 UTC, frol commented
@khorolets there are more places where the changes I proposed need to be copied over

2021-08-20 09:57 UTC, khorolets commented
> @khorolets there are more places where the changes I proposed need to be copied over / re-applied

OK, I guess I've done it this time

2021-08-20 10:00 UTC, khorolets commented
> @khorolets there are more places where the changes I proposed need to be copied over / re-applied

OK, I guess I've done it this time

2021-08-23 13:56 UTC, khorolets commented
@thisisjoshford could you assist with failing test-links, please? :)

2021-08-23 14:58 UTC, bucanero commented
> @thisisjoshford could you assist with failing test-links, please? :)

Hello @khorolets, I have reviewed/fixed some broken links, but there's still one dead URL that I don't know how to handle: `https://ropsten.bridgetonear.org/`

The server seems down so I don't know if it's a temporary issue or not. Maybe Josh knows better! 😄

2021-08-24 11:33 UTC, merged

2021-08-24 11:34 UTC, frol commented
The failing test is not related to the PR, so I merged this PR. @bucanero @thisisjoshford Please, double check if we even need that bridge documentation with @djsatok or @artob